### ISSUE TITLE
[REQ] Kick player only when player chooses a team

### ISSUE THREAD

**Issue by crashzk** [NockyCZ/CS2-ReservedSlots#2]
Would it be possible to have a method of kicking a player only when the player with privileges chooses to join a team?

It would add a new `Kick type` which would be to kick a player only if the VIP chooses a team to join, then it would kick the last player who joined the team.

This new kick option could only work with the `Reserved slots method - 3`.

**Comment by NockyCZ** [comment]
And whats the difference from being kicked out when they connect? :D

**Comment by crashzk** [comment]
> And whats the difference from being kicked out when they connect? :D

Often, in my case, players with VIP connect but don't like to join the teams directly. They like to wait a little and only then choose a team and enter, they remain a spectator.

Besides, just using the `Reserved slots method - 3` currently no one would be kicked from what I understand, it is only kicked after the server is full and if you are not a VIP and try to connect you are kicked, VIP connects normally even with a full server.

But after the VIP connects, what can he do to kick a player to play? So no one who is already connected is kicked, VIP becomes a spectator?

Example, I have a 12 slot, competitive/pug server.
- 12 players on the server, all players do not have VIP
- VIP connects even if there are 12 players already, no one gets kicked

This raises the question: how will a VIP join a team if they can't kick anyone after connecting?

**Comment by crashzk** [comment]
I know the simple solution would be to add a kick option for VIPS, but I wouldn't want to use this feature, as they can kick any player at any time.

With the method I mentioned above, he can only kick by choosing a team to join. Chose a team, join, kick a player.

**Comment by NockyCZ** [comment]
Maybe sometime in the future I'll add it, no time now :D

**Comment by crashzk** [comment]
Doubt, with this new version would the feature requested above be possible?

Still not right?

**Comment by crashzk** [comment]
I believe that for my suggestion I would need the `"Reserved slots method": 3`, where no player is kicked if someone enters with the flags of `"Flag for reserved slots": "@css/reservation"` and/or `"Admin flag for reserved slots": "@css/ban"`. Player would only be kicked if the player with privileges chooses a team to join.

Then I would use some of the `"Kick type"` methods to kick out the player.

**Comment by crashzk** [comment]
Detailed explanation of each method would be.

- `Reserved slots method: 3` - Does not expel any player when connecting, only when the player with privileges chooses a team to join - if you join from SPEC, no one is kicked. It does not take into account the `Reserved slots` configuration, it ignores it.

For example, if the server has 12 slots and a VIP connects, no one is expelled until they choose CT or TR to enter, then one of the team they choose is expelled.

If the server is already full, 12 players only players with flags can connect, whoever does not have a flag is kicked if the server is full.

Anyway, anything just get in touch so we can explain everything.

**Comment by NockyCZ** [comment]
Added - https://github.com/NockyCZ/CS2-ReservedSlots/releases/tag/v1.0.6
