### ISSUE TITLE
server showing full but in game one slot is missing 

### ISSUE THREAD

**Issue by mayersgamer** [NockyCZ/CS2-ReservedSlots#3]
- i want the server to let all players join 22/22 slot then if an admin want to join it will kick the players with worst ping 
right now method 3 using and on my 22 slot server always 21 can join and that one slot is gone to waste . 
10 ct 10 t 1 spec = 21 not 22 , but the steam game server is showing 22/22
- and i have suggestion , players are asking me why were kicked ! the message showing when they get kicked is just "kicked by server" maybe it should be "server is full" .

thank you !

**Comment by NockyCZ** [comment]
1. Method 3 is disabled for now because it does not work properly
2. It is not possible to set custom kick message for now
