### ISSUE TITLE
[Enhancement] Don't kick a player if someone with a certain flag joins

### ISSUE THREAD

**Issue by iCallH4x** [NockyCZ/CS2-ReservedSlots#4]
Grant the ability to add a flag that allows an admin to join even if the server's full, but not kick a player (fill up the +1 slot). This allows admins to join and spectate players when dealing with reports without potentially kicking the player that has been reported. Sort of like a stealth mode I guess?

**Comment by NockyCZ** [comment]
Okay, i will add a new reserved method

**Comment by iCallH4x** [comment]
My suggestion would just be an extra modification of method 0 by the way, I'm not too good at explaining things but I think the flag check would be better as an additional config option for method 0.

Thank you for the quick response by the way, I appreciate it!

EDIT: I think this would work perfectly in conjunction with Issue https://github.com/NockyCZ/CS2-ReservedSlots/issues/2, just check the admin bypass flag on joining to bypass the kick until they pick a team, and don't kick if they join spectate.

**Comment by NockyCZ** [comment]
Oh, yeah i get it 😄

**Comment by NockyCZ** [comment]
Added - https://github.com/NockyCZ/CS2-ReservedSlots/releases/tag/v1.0.5
