### ISSUE TITLE
[REQ] Kick messages

### ISSUE THREAD

**Issue by crashzk** [NockyCZ/CS2-ReservedSlots#5]
We could have some kick messages, announcements, etc.

- `"announcement.slot.full"` - Server is full - Slot Reserved For Vips Only
  - It would show when the teams are full and not allow another player to enter until someone leaves or is kicked out of the reserved VIP slot.
- `"announcement.kick.player.joined"` - **{NAMEVIP}** kicked **{TARGETPLAYER}** due to reserved slot.
- `"announcement.kick"` - **{TARGETPLAYER}** kicked due to reserved slot.

In other words, a kick message for the player who was kicked due to the reserved slot. Message would show both on the server for all players to view and for the player as a reason. (I understand that CS2 currently does not allow changing the reason for the kick, but I believe it can be shown in the console of the player who was kicked)

Message from full teams, with no vacancies on the teams, that you must be a VIP to kick someone and take the player's place.

**Comment by NockyCZ** [comment]
Added https://github.com/NockyCZ/CS2-ReservedSlots/releases/tag/v1.0.7
